import type { Project } from '../types';

export const projects: Project[] = [
  {
    id: 'uom-mba',
    title: 'University of Moratuwa MBA Program',
    description: 'A professional website for the MBA in Management of Technology program at the University of Moratuwa, featuring course details, faculty profiles, and online application.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Increased online applications by 40%',
    link: 'https://mba.mot.uom.lk/',
    featured: true,
  },
  {
    id: 'uom-conference',
    title: 'University of Moratuwa Conference',
    description: 'An official conference website for the University of Moratuwa, providing event schedules, speaker information, paper submissions, and registration for attendees.',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Successfully managed 500+ conference registrations',
    link: '#',
    featured: true,
  },
  {
    id: 'oasis-travel',
    title: 'Oasis Travel',
    description: 'A full-featured travel agency website showcasing holiday packages, tour itineraries, and online booking for one of Sri Lanka\'s leading travel companies.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Boosted online bookings by 60%',
    link: 'http://oasistravel.lk/',
    featured: true,
  },
  {
    id: 'golden-coconut',
    title: 'Golden Coconut Holiday',
    description: 'A vibrant travel and holiday website for Golden Coconut Holiday, highlighting Sri Lanka tour packages, hotel recommendations, and seamless travel planning.',
    image: 'https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Expanded customer reach across 15 countries',
    link: 'https://goldencoconutholiday.com/',
    featured: true,
  },
  {
    id: 'slstl',
    title: 'SLSTL Travel & Leisure',
    description: 'A modern travel and leisure website built for SLSTL, offering curated Sri Lanka travel experiences, corporate tour packages, and tailored holiday solutions.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Increased organic traffic by 80%',
    link: 'https://slstl.lk/',
    featured: true,
  },
];

export const projectCategories = ['Web Development'];
