import type { Project } from '../types';

export const projects: Project[] = [
  {
    id: 'uom-mba',
    title: 'University of Moratuwa — MBA in Management of Technology',
    description: 'Official website for the MBA in Management of Technology program at the Department of Management of Technology (MOT), University of Moratuwa. Features intake information, program details, and application resources.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Streamlined student intake and application process online',
    link: 'https://mba.mot.uom.lk/',
    featured: true,
  },
  {
    id: 'slstl',
    title: 'SLSTL — Sri Lanka Society of Transport & Logistics',
    description: 'Website for the only professional body in Transport & Logistics in Sri Lanka, whose members hold post-graduate qualifications. Covers membership, the R4TLI Conference, JSALT journal, events, and orders.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Unified membership management and conference registration online',
    link: 'https://slstl.lk/',
    featured: true,
  },
  {
    id: 'oasis-travel',
    title: 'Oasis Travel — Explore Amazing Sri Lanka',
    description: 'A full-featured travel agency website for Oasis Travel offering Sri Lanka holiday and tour packages. Includes tours, destinations, experiences, FAQs, and a multilingual interface for international visitors.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Increased online tour inquiries and international reach',
    link: 'http://oasistravel.lk/',
    featured: true,
  },
  {
    id: 'golden-coconut',
    title: 'Golden Coconut Holiday — Journeys & Stories: Sri Lanka Unveiled',
    description: 'International travel agency website showcasing curated Sri Lanka experiences — from untamed jungles and golden shores to ancient temples and vibrant traditions. Features destinations, experiences, and news.',
    image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Expanded customer reach across multiple countries',
    link: 'https://goldencoconutholiday.com/',
    featured: true,
  },
  {
    id: 'uom-conference',
    title: 'University of Moratuwa — Academic Conference',
    description: 'Official conference website for the University of Moratuwa providing event schedules, speaker information, paper submission guidelines, and online registration for academic attendees.',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['WordPress', 'PHP', 'MySQL', 'CSS3'],
    outcome: 'Successfully managed conference registrations and submissions online',
    link: '#',
    featured: true,
  },
];

export const projectCategories = ['Web Development'];
