import type { Project } from '../types';

export const projects: Project[] = [
  {
    id: 'ecommerce-platform',
    title: 'Global E-Commerce Platform',
    description: 'Built a scalable e-commerce platform handling 100K+ daily transactions with real-time inventory management and personalized recommendations.',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'AWS'],
    outcome: '300% increase in conversion rate and 99.9% uptime',
    featured: true,
  },
  {
    id: 'healthcare-app',
    title: 'Telehealth Mobile App',
    description: 'Developed a HIPAA-compliant mobile application connecting patients with healthcare providers through video consultations.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop',
    category: 'Mobile Development',
    technologies: ['React Native', 'WebRTC', 'Firebase', 'Stripe'],
    outcome: '50K+ active users and 4.8-star rating',
    featured: true,
  },
  {
    id: 'fintech-dashboard',
    title: 'FinTech Analytics Dashboard',
    description: 'Created an advanced analytics dashboard for financial data visualization with real-time market updates and custom reporting.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['TypeScript', 'D3.js', 'Express', 'MongoDB', 'Socket.io'],
    outcome: 'Reduced reporting time by 80%',
    featured: true,
  },
  {
    id: 'saas-platform',
    title: 'Project Management SaaS',
    description: 'Built a comprehensive project management platform with team collaboration, time tracking, and resource allocation features.',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['Next.js', 'Prisma', 'tRPC', 'Tailwind CSS', 'Vercel'],
    outcome: '10K+ teams onboarded in first year',
    featured: false,
  },
  {
    id: 'ai-chatbot',
    title: 'AI-Powered Customer Support',
    description: 'Implemented an intelligent chatbot using natural language processing to automate customer support inquiries.',
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800&h=600&fit=crop',
    category: 'AI & ML',
    technologies: ['Python', 'TensorFlow', 'React', 'FastAPI', 'OpenAI'],
    outcome: '70% reduction in support ticket volume',
    featured: false,
  },
  {
    id: 'food-delivery',
    title: 'Food Delivery Mobile App',
    description: 'Developed a full-stack food delivery application with real-time order tracking and payment integration.',
    image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=600&fit=crop',
    category: 'Mobile Development',
    technologies: ['Flutter', 'Node.js', 'MongoDB', 'Google Maps API'],
    outcome: '25K+ downloads in first month',
    featured: false,
  },
  {
    id: 'cms-redesign',
    title: 'Enterprise CMS Redesign',
    description: 'Redesigned and rebuilt a legacy content management system with modern UX principles and improved performance.',
    image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
    category: 'UI/UX Design',
    technologies: ['Figma', 'React', 'Headless CMS', 'GraphQL'],
    outcome: '60% faster page load times',
    featured: false,
  },
  {
    id: 'blockchain-wallet',
    title: 'Cryptocurrency Wallet',
    description: 'Built a secure multi-currency cryptocurrency wallet with advanced security features and portfolio tracking.',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['React', 'Web3.js', 'Ethereum', 'MetaMask'],
    outcome: 'Secured $10M+ in digital assets',
    featured: false,
  },
  {
    id: 'social-network',
    title: 'Professional Networking Platform',
    description: 'Created a niche social network for industry professionals with job postings, networking, and content sharing.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    category: 'Web Development',
    technologies: ['Vue.js', 'Django', 'PostgreSQL', 'ElasticSearch'],
    outcome: '100K+ registered professionals',
    featured: true,
  },
];

export const projectCategories = [
  'All',
  'Web Development',
  'Mobile Development',
  'UI/UX Design',
  'AI & ML',
  'Cloud Solutions',
];
