import type { Service } from '../types';

export const services: Service[] = [
  {
    id: 'web-development',
    title: 'Web Development',
    description: 'Build fast, scalable, and responsive web applications using modern technologies and frameworks.',
    icon: 'Code2',
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&h=600&fit=crop',
    features: [
      'Custom web application development',
      'Progressive Web Apps (PWA)',
      'E-commerce solutions',
      'Content Management Systems',
      'API integration and development',
      'Performance optimization',
    ],
  },
  {
    id: 'mobile-development',
    title: 'Mobile Development',
    description: 'Create native and cross-platform mobile applications that deliver exceptional user experiences.',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop',
    features: [
      'iOS and Android development',
      'React Native applications',
      'Flutter applications',
      'Mobile UI/UX design',
      'App Store deployment',
      'Mobile app maintenance',
    ],
  },
  {
    id: 'ui-ux-design',
    title: 'UI/UX Design',
    description: 'Design beautiful, intuitive interfaces that users love and that drive business results.',
    icon: 'Palette',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
    features: [
      'User research and testing',
      'Wireframing and prototyping',
      'Visual design and branding',
      'Design systems creation',
      'Responsive design',
      'Accessibility compliance',
    ],
  },
  {
    id: 'cloud-solutions',
    title: 'Cloud Solutions',
    description: 'Deploy and manage scalable cloud infrastructure with industry-leading platforms.',
    icon: 'Cloud',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop',
    features: [
      'AWS, Azure, and GCP deployment',
      'Cloud migration services',
      'DevOps and CI/CD',
      'Containerization with Docker/Kubernetes',
      'Serverless architecture',
      'Cloud security and monitoring',
    ],
  },
  {
    id: 'software-consulting',
    title: 'Software Consulting',
    description: 'Get expert guidance on technology strategy, architecture, and best practices.',
    icon: 'Users',
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=600&fit=crop',
    features: [
      'Technology stack selection',
      'Architecture design and review',
      'Code quality audits',
      'Performance optimization',
      'Team training and mentorship',
      'Project rescue and recovery',
    ],
  },
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    description: 'Leverage artificial intelligence and machine learning to solve complex business problems.',
    icon: 'Brain',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop',
    features: [
      'Custom AI model development',
      'Natural language processing',
      'Computer vision solutions',
      'Predictive analytics',
      'AI integration services',
      'ML model deployment and monitoring',
    ],
  },
];
